In [1]:
import tensorflow as tf

In [3]:
#二维tensor的pad
a = tf.reshape(tf.range(9),[3,3])
a

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=int32)>

In [4]:
tf.pad(a,[[1,0],[0,0]])     #对行pad，上面加一行，下面不加，对列pad，左右不加

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=int32)>

In [5]:
tf.pad(a,[[1,1],[0,0]])     #对行，上下各加一行

<tf.Tensor: shape=(5, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 0, 0]], dtype=int32)>

In [6]:
tf.pad(a,[[1,0],[0,1]])

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[0, 0, 0, 0],
       [0, 1, 2, 0],
       [3, 4, 5, 0],
       [6, 7, 8, 0]], dtype=int32)>

In [10]:
#高维度tensor的pad
a = tf.random.normal([4,28,28,3])            #理解成四张图片
b = tf.pad(a,[[0,0],[2,2],[2,2],[0,0]])         #对图片的高和宽进行pad，上下左右都加2行像素
b.shape

TensorShape([4, 32, 32, 3])