# 线性代数

In [1]:
import numpy as np

In [15]:
A=np.array([[3,3],[2,4]])
A

array([[3, 3],
       [2, 4]])

In [16]:
a, b = np.linalg.eig(A)

In [17]:
a

array([1., 6.])

In [18]:
b

array([[-0.83205029, -0.70710678],
       [ 0.5547002 , -0.70710678]])

# 概率论