In [1]:
import tensorflow as tf

In [2]:
a = tf.ones([1,5,5,3])

In [3]:
#按层索引
a[0][0]    

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [4]:
a[0][0][0]

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 1., 1.], dtype=float32)>

In [5]:
a[0][0][0][2]

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

### numpy风格的索引方式，性能更好

In [23]:
a = tf.random.normal([4,28,28,3])

In [7]:
a[1].shape

TensorShape([28, 28, 3])

In [8]:
a[1,2].shape

TensorShape([28, 3])

In [9]:
a[1,2,3].shape

TensorShape([3])

In [12]:
a[1,2,3,2].shape     #标量

TensorShape([])

In [15]:
a = tf.range(10)
a

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [16]:
a[-1:]           #切片操作总是返回一个向量！！

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([9], dtype=int32)>

In [17]:
a[-2]

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [18]:
a[-2:]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([8, 9], dtype=int32)>

In [19]:
a[:2]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([0, 1], dtype=int32)>

In [21]:
a[:-1]         #前闭后开    闭区间、开区间

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)>

In [25]:
a = tf.random.normal([4,28,28,3])
a.shape

TensorShape([4, 28, 28, 3])

In [26]:
a[0].shape

TensorShape([28, 28, 3])

In [27]:
a[:,:,:,2]     #将所有数据按单通道采样

<tf.Tensor: shape=(4, 28, 28), dtype=float32, numpy=
array([[[ 1.1144309 , -0.5831978 , -0.04076265, ..., -1.1342124 ,
         -0.13980521, -0.30124027],
        [-0.01220568, -0.62734276, -0.62601876, ...,  1.302717  ,
         -0.9274531 , -2.151871  ],
        [ 0.16744748, -1.6427945 , -0.91035765, ..., -0.01067297,
          0.09157666,  1.53967   ],
        ...,
        [-0.44873175, -0.685864  ,  1.2281187 , ...,  0.06693294,
          0.8301872 , -0.92129105],
        [-1.1965489 , -0.9293928 ,  0.6538647 , ..., -0.08286531,
         -0.8028312 , -0.6553918 ],
        [-1.1762129 ,  2.243356  ,  1.3172343 , ..., -1.6803027 ,
         -0.83972704, -1.5510244 ]],

       [[ 0.05500869, -0.44436067,  1.4012723 , ..., -0.06148794,
         -0.70074975,  0.63569194],
        [ 2.1426415 , -1.3233774 ,  0.3292605 , ..., -0.5657716 ,
         -0.56423444, -1.3569555 ],
        [-0.17000973, -0.72350675, -0.45106897, ..., -0.7234751 ,
          0.87139255,  0.548732  ],
        ...,
 

#### 按一定间隔进行采样：


In [29]:
a[:,:,:,::2]     #取0、2通道，隔一个采样一次

<tf.Tensor: shape=(4, 28, 28, 2), dtype=float32, numpy=
array([[[[ 1.676847  ,  1.1144309 ],
         [-0.10825591, -0.5831978 ],
         [-0.03269015, -0.04076265],
         ...,
         [-0.59445655, -1.1342124 ],
         [-1.5333444 , -0.13980521],
         [-0.40363   , -0.30124027]],

        [[-0.25054675, -0.01220568],
         [-0.12364548, -0.62734276],
         [ 0.10038579, -0.62601876],
         ...,
         [-0.976738  ,  1.302717  ],
         [ 0.8308164 , -0.9274531 ],
         [ 2.0178668 , -2.151871  ]],

        [[ 0.9637188 ,  0.16744748],
         [ 0.77360445, -1.6427945 ],
         [-1.121827  , -0.91035765],
         ...,
         [-1.6037145 , -0.01067297],
         [ 0.52455515,  0.09157666],
         [-0.10111243,  1.53967   ]],

        ...,

        [[ 1.7295245 , -0.44873175],
         [ 0.17446285, -0.685864  ],
         [-0.41162187,  1.2281187 ],
         ...,
         [-0.38169843,  0.06693294],
         [ 1.2706078 ,  0.8301872 ],
         [ 3.0031

### 三点省略号切片

In [31]:
a = tf.random.normal([2,4,28,28,3])

In [33]:
a[0,...,2].shape

TensorShape([4, 28, 28])

In [34]:
#等同于
a[0,:,:,:,2].shape

TensorShape([4, 28, 28])

## Selective Indexing 