In [3]:
import tensorflow as tf

In [2]:
%pip install tensorflow

     |████████████████████████████████| 394.3 MB 30 kB/s s eta 0:00:01   |▉                               | 10.8 MB 6.0 MB/s eta 0:01:04     |█████▎                          | 65.1 MB 22.5 MB/s eta 0:00:15     |████████████                    | 147.7 MB 17.7 MB/s eta 0:00:14     |██████████████▍                 | 177.5 MB 19.2 MB/s eta 0:00:12     |████████████████▎               | 201.0 MB 35.4 MB/s eta 0:00:06     |████████████████████            | 246.0 MB 44.7 MB/s eta 0:00:04     |████████████████████▉           | 256.2 MB 41.7 MB/s eta 0:00:04     |██████████████████████▉         | 280.9 MB 8.5 MB/s eta 0:00:14     |█████████████████████████▋      | 315.9 MB 25.1 MB/s eta 0:00:04     |██████████████████████████▏     | 322.6 MB 35.0 MB/s eta 0:00:03     |██████████████████████████▊     | 329.3 MB 35.0 MB/s eta 0:00:02     |████████████████████████████▊   | 354.0 MB 26.8 MB/s eta 0:00:02     |████████████████████████████▉   | 355.5 MB 26.8 MB/s eta 0:00:02     |████████████████████

Note: you may need to restart the kernel to use updated packages.


In [2]:
a = tf.ones([1,5,5,3])

In [3]:
#按层索引
a[0][0]    

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [4]:
a[0][0][0]

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 1., 1.], dtype=float32)>

In [5]:
a[0][0][0][2]

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

### numpy风格的索引方式，性能更好

In [23]:
a = tf.random.normal([4,28,28,3])

In [7]:
a[1].shape

TensorShape([28, 28, 3])

In [8]:
a[1,2].shape

TensorShape([28, 3])

In [9]:
a[1,2,3].shape

TensorShape([3])

In [12]:
a[1,2,3,2].shape     #标量

TensorShape([])

In [15]:
a = tf.range(10)
a

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [16]:
a[-1:]           #切片操作总是返回一个向量！！

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([9], dtype=int32)>

In [17]:
a[-2]

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [18]:
a[-2:]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([8, 9], dtype=int32)>

In [19]:
a[:2]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([0, 1], dtype=int32)>

In [21]:
a[:-1]         #前闭后开    闭区间、开区间

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)>

In [25]:
a = tf.random.normal([4,28,28,3])
a.shape

TensorShape([4, 28, 28, 3])

In [26]:
a[0].shape

TensorShape([28, 28, 3])

In [27]:
a[:,:,:,2]     #将所有数据按单通道采样

<tf.Tensor: shape=(4, 28, 28), dtype=float32, numpy=
array([[[ 1.1144309 , -0.5831978 , -0.04076265, ..., -1.1342124 ,
         -0.13980521, -0.30124027],
        [-0.01220568, -0.62734276, -0.62601876, ...,  1.302717  ,
         -0.9274531 , -2.151871  ],
        [ 0.16744748, -1.6427945 , -0.91035765, ..., -0.01067297,
          0.09157666,  1.53967   ],
        ...,
        [-0.44873175, -0.685864  ,  1.2281187 , ...,  0.06693294,
          0.8301872 , -0.92129105],
        [-1.1965489 , -0.9293928 ,  0.6538647 , ..., -0.08286531,
         -0.8028312 , -0.6553918 ],
        [-1.1762129 ,  2.243356  ,  1.3172343 , ..., -1.6803027 ,
         -0.83972704, -1.5510244 ]],

       [[ 0.05500869, -0.44436067,  1.4012723 , ..., -0.06148794,
         -0.70074975,  0.63569194],
        [ 2.1426415 , -1.3233774 ,  0.3292605 , ..., -0.5657716 ,
         -0.56423444, -1.3569555 ],
        [-0.17000973, -0.72350675, -0.45106897, ..., -0.7234751 ,
          0.87139255,  0.548732  ],
        ...,
 

#### 按一定间隔进行采样：


In [29]:
a[:,:,:,::2]     #取0、2通道，隔一个采样一次

<tf.Tensor: shape=(4, 28, 28, 2), dtype=float32, numpy=
array([[[[ 1.676847  ,  1.1144309 ],
         [-0.10825591, -0.5831978 ],
         [-0.03269015, -0.04076265],
         ...,
         [-0.59445655, -1.1342124 ],
         [-1.5333444 , -0.13980521],
         [-0.40363   , -0.30124027]],

        [[-0.25054675, -0.01220568],
         [-0.12364548, -0.62734276],
         [ 0.10038579, -0.62601876],
         ...,
         [-0.976738  ,  1.302717  ],
         [ 0.8308164 , -0.9274531 ],
         [ 2.0178668 , -2.151871  ]],

        [[ 0.9637188 ,  0.16744748],
         [ 0.77360445, -1.6427945 ],
         [-1.121827  , -0.91035765],
         ...,
         [-1.6037145 , -0.01067297],
         [ 0.52455515,  0.09157666],
         [-0.10111243,  1.53967   ]],

        ...,

        [[ 1.7295245 , -0.44873175],
         [ 0.17446285, -0.685864  ],
         [-0.41162187,  1.2281187 ],
         ...,
         [-0.38169843,  0.06693294],
         [ 1.2706078 ,  0.8301872 ],
         [ 3.0031

### 三点省略号切片

In [9]:
a = tf.random.normal([3,4,28,28,3])

In [10]:
a[0,...,2].shape

TensorShape([4, 28, 28])

In [11]:
#等同于
a[0,:,:,:,2].shape

TensorShape([4, 28, 28])

## Selective Indexing   更加灵活的采样，实现无规律index采样

### tf.gather:对某一个维度进行更加灵活采样，而其他维度保持不变

In [14]:
tf.gather(a,axis=0,indices=[1,2]).shape       #对第一个维度，取1、2通道

TensorShape([2, 4, 28, 28, 3])

In [16]:
a[1:3].shape      #与上面等同

TensorShape([2, 4, 28, 28, 3])

In [17]:
tf.gather(a,axis=0,indices=[2,0,1])      #对第一个维度进行重新排序

<tf.Tensor: shape=(3, 4, 28, 28, 3), dtype=float32, numpy=
array([[[[[-1.00241387e+00,  7.25482941e-01, -1.17221975e+00],
          [-2.53355742e-01,  1.42013058e-01, -9.19954240e-01],
          [ 1.57650664e-01,  4.34615582e-01, -7.72990286e-01],
          ...,
          [ 1.32391319e-01,  7.16232955e-01, -9.76897404e-02],
          [-1.73359722e-01,  1.70857596e+00, -1.47883499e+00],
          [-3.55811238e-01,  4.44417298e-01, -2.57844567e+00]],

         [[-1.81985343e+00,  3.59569997e-01,  3.59572291e-01],
          [ 8.88837993e-01, -2.46776566e-01, -1.77487159e+00],
          [ 1.73203814e+00, -3.50650936e-01, -8.56968641e-01],
          ...,
          [ 1.35861039e+00, -1.88288128e+00,  4.27402288e-01],
          [-1.31442380e+00,  1.05831638e-01, -4.04459089e-02],
          [ 5.66748753e-02,  1.89743936e+00, -1.08479428e+00]],

         [[-1.35600913e+00, -3.76623392e-01, -1.44470119e+00],
          [ 5.72635531e-01,  6.67804778e-01, -1.36808920e+00],
          [ 1.07196677e+0

In [18]:
tf.gather(a,axis=2,indices=[2,3,7,9,0]).shape

TensorShape([3, 4, 5, 28, 3])

### tf.gather_nd:对多个维度进行多通道采样

In [36]:
a.shape

TensorShape([3, 4, 28, 28, 3])

In [37]:
tf.gather_nd(a,[0]).shape    #取第一个维度的第一个通道

TensorShape([4, 28, 28, 3])

In [21]:
tf.gather_nd(a,[0,1]).shape     #取第一个维度的第一个通道，第二个维度的第二个通道

TensorShape([28, 28, 3])

In [22]:
tf.gather_nd(a,[0,1,12,15,2]).shape    #取1维度的1通道，二维度的2通道，三维度的13通道，四维度的16通道，最后一个维度的第三个通道，是一个标量

TensorShape([])

In [23]:
tf.gather_nd(a,[[0,1,12,15,2]]).shape     #这里也是取出一个值，但是是向量

TensorShape([1])

In [24]:
a.shape

TensorShape([3, 4, 28, 28, 3])

In [25]:
tf.gather_nd(a,[[0,0],[1,1]]).shape    #第一维度取第一个通道，第二维度取第一个通道；第一维度取第二个通道，第二维度取第二个通道，然后拼接起来

TensorShape([2, 28, 28, 3])

In [26]:
tf.gather_nd(a,[[0,0],[1,1],[2,3]]).shape

TensorShape([3, 28, 28, 3])

In [27]:
tf.gather_nd(a,[[0,0,0],[1,1,2],[2,3,10]]).shape

TensorShape([3, 28, 3])

### tf.boolean_mask ：类似tf.gather

In [31]:
a.shape

TensorShape([3, 4, 28, 28, 3])

In [33]:
tf.boolean_mask(a,mask=[True,True,False]).shape     #对第一个维度的三个通道进行选择

TensorShape([2, 4, 28, 28, 3])

In [38]:
tf.boolean_mask(a,mask=[True,True,True,False],axis=1).shape     #对第二个维度的四个通道进行选取

TensorShape([3, 3, 28, 28, 3])

In [39]:
#对第一个维度的三个通道分别进行采样，每个通道下有四个第二维度的数据，所以总共是12个通道
tf.boolean_mask(a,mask=[[False,True,True,False],[True,False,True,False],[True,True,False,False]])     #一共取了六个通道

<tf.Tensor: shape=(6, 28, 28, 3), dtype=float32, numpy=
array([[[[ 1.00920248e+00, -4.80703533e-01,  9.19075459e-02],
         [ 1.28974748e+00,  1.48861483e-01, -1.30699456e-01],
         [ 1.16354299e+00, -8.59926641e-01,  5.98222673e-01],
         ...,
         [-2.35556409e-01, -4.40726280e-01,  1.01967478e+00],
         [-1.63549960e+00,  8.60728681e-01,  1.64420056e+00],
         [-9.02572155e-01,  1.55107722e-01,  1.01246290e-01]],

        [[ 6.63308501e-01, -1.93611050e+00,  1.83012772e+00],
         [-2.51500607e-01,  1.17851472e+00,  5.55786312e-01],
         [-3.83741230e-01, -5.73017955e-01, -3.12307060e-01],
         ...,
         [ 6.88545406e-01,  3.67403448e-01,  1.88361496e-01],
         [-2.20114374e+00,  2.08889318e+00, -7.48193383e-01],
         [-4.77657169e-01,  1.37574971e-01, -2.04918846e-01]],

        [[ 1.48303628e+00, -5.54262161e-01,  6.77640676e-01],
         [-6.71107352e-01, -1.25256240e+00, -4.80720878e-01],
         [ 1.47127247e+00,  3.07435226e+00, 