In [1]:
import tensorflow as tf

In [2]:
#通过numpy创建
import numpy as np

In [3]:
tf.convert_to_tensor(np.ones([2,3]))

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]])>

In [4]:
tf.convert_to_tensor(np.zeros([2,3]))

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]])>

In [5]:
tf.convert_to_tensor([1,2])

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [6]:
#注意，数据类型需要一致
tf.convert_to_tensor([1,(1,2)])

ValueError: Can't convert Python sequence with mixed types to Tensor.

## 直接通过tensorflow创建

In [7]:

tf.zeros([])    #创建一个标量

<tf.Tensor: shape=(), dtype=float32, numpy=0.0>

In [8]:
tf.zeros([1])     #创建一个1维数据

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>

In [9]:
#注意，这里的[2,3]不是数据，而是要创建的数据的shape
tf.zeros([2,3])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [12]:
a = tf.ones([2,3,3])
a

<tf.Tensor: shape=(2, 3, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [13]:
#创建一个shape相同，数据全0的数据
tf.zeros_like(a)

<tf.Tensor: shape=(2, 3, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

In [14]:
tf.ones([2,3])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

### 填充任意元素

In [15]:
tf.fill([2,2],10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 10],
       [10, 10]], dtype=int32)>

In [16]:
tf.fill([3,5],2.1)

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[2.1, 2.1, 2.1, 2.1, 2.1],
       [2.1, 2.1, 2.1, 2.1, 2.1],
       [2.1, 2.1, 2.1, 2.1, 2.1]], dtype=float32)>

### 创建正态分布数据

In [17]:
tf.random.normal([2,2],mean=1,stddev=1)    #均值为1方差1

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.08492291,  1.239416  ],
       [ 2.5550785 ,  1.6184435 ]], dtype=float32)>

In [18]:
tf.random.normal([2,2])      #标准正态分布

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.19012694,  0.7920874 ],
       [ 0.531189  , -0.17139138]], dtype=float32)>

In [19]:
tf.random.truncated_normal([2,2],mean=0,stddev=1)       #截断的正态分布

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.16926305, -1.0626482 ],
       [-0.9450281 ,  1.242686  ]], dtype=float32)>

### 均匀分布

In [21]:
tf.random.uniform([2,2],minval=0,maxval=1)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.65244544, 0.16029215],
       [0.3045181 , 0.5259417 ]], dtype=float32)>

In [22]:
tf.random.uniform([3,3],minval=-10,maxval=10)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-8.781815 , -3.3983183, -2.4781322],
       [ 5.9951134, -5.4604363,  6.318199 ],
       [ 9.132616 , -7.7978683,  4.476263 ]], dtype=float32)>

In [24]:
tf.random.uniform([3,3],minval=-10,maxval=10,dtype=tf.int32)    #指定数据类型

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[-3,  5,  1],
       [ 7,  3,  0],
       [ 8,  9, -4]], dtype=int32)>