In [3]:
import tensorflow as tf

In [2]:
%pip install tensorflow

     |████████████████████████████████| 394.3 MB 13 kB/s s eta 0:00:01     |███████████████████████████▍    | 337.3 MB 49.1 MB/s eta 0:00:02
     |████████████████████████████████| 65 kB 4.8 MB/s  eta 0:00:01
     |████████████████████████████████| 1.0 MB 28.8 MB/s eta 0:00:01
     |████████████████████████████████| 10.6 MB 38.3 MB/s eta 0:00:01
     |████████████████████████████████| 14.8 MB 48.5 MB/s eta 0:00:01
     |████████████████████████████████| 57 kB 4.5 MB/s  eta 0:00:01
     |████████████████████████████████| 42 kB 1.9 MB/s  eta 0:00:01
     |████████████████████████████████| 462 kB 41.0 MB/s eta 0:00:01
     |████████████████████████████████| 2.9 MB 57.8 MB/s eta 0:00:01
     |████████████████████████████████| 127 kB 70.9 MB/s eta 0:00:01
     |████████████████████████████████| 3.8 MB 58.4 MB/s eta 0:00:01
     |████████████████████████████████| 96 kB 8.3 MB/s  eta 0:00:01
     |████████████████████████████████| 116 kB 68.6 MB/s eta 0:00:01
     |███████████████████████████

In [2]:
#通过numpy创建
import numpy as np

In [3]:
tf.convert_to_tensor(np.ones([2,3]))

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]])>

In [4]:
tf.convert_to_tensor(np.zeros([2,3]))

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]])>

In [5]:
tf.convert_to_tensor([1,2])

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [6]:
#注意，数据类型需要一致
tf.convert_to_tensor([1,(1,2)])

ValueError: Can't convert Python sequence with mixed types to Tensor.

## 直接通过tensorflow创建

In [7]:

tf.zeros([])    #创建一个标量

<tf.Tensor: shape=(), dtype=float32, numpy=0.0>

In [8]:
tf.zeros([1])     #创建一个1维数据

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>

In [9]:
#注意，这里的[2,3]不是数据，而是要创建的数据的shape
tf.zeros([2,3])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [12]:
a = tf.ones([2,3,3])
a

<tf.Tensor: shape=(2, 3, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [13]:
#创建一个shape相同，数据全0的数据
tf.zeros_like(a)

<tf.Tensor: shape=(2, 3, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

In [14]:
tf.ones([2,3])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

### 填充任意元素

In [15]:
tf.fill([2,2],10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 10],
       [10, 10]], dtype=int32)>

In [16]:
tf.fill([3,5],2.1)

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[2.1, 2.1, 2.1, 2.1, 2.1],
       [2.1, 2.1, 2.1, 2.1, 2.1],
       [2.1, 2.1, 2.1, 2.1, 2.1]], dtype=float32)>

### 创建正态分布数据

In [17]:
tf.random.normal([2,2],mean=1,stddev=1)    #均值为1方差1

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.08492291,  1.239416  ],
       [ 2.5550785 ,  1.6184435 ]], dtype=float32)>

In [18]:
tf.random.normal([2,2])      #标准正态分布

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.19012694,  0.7920874 ],
       [ 0.531189  , -0.17139138]], dtype=float32)>

In [19]:
tf.random.truncated_normal([2,2],mean=0,stddev=1)       #截断的正态分布

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.16926305, -1.0626482 ],
       [-0.9450281 ,  1.242686  ]], dtype=float32)>

### 均匀分布Uniform

In [21]:
tf.random.uniform([2,2],minval=0,maxval=1)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.65244544, 0.16029215],
       [0.3045181 , 0.5259417 ]], dtype=float32)>

In [22]:
tf.random.uniform([3,3],minval=-10,maxval=10)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-8.781815 , -3.3983183, -2.4781322],
       [ 5.9951134, -5.4604363,  6.318199 ],
       [ 9.132616 , -7.7978683,  4.476263 ]], dtype=float32)>

In [24]:
tf.random.uniform([3,3],minval=-10,maxval=10,dtype=tf.int32)    #指定数据类型

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[-3,  5,  1],
       [ 7,  3,  0],
       [ 8,  9, -4]], dtype=int32)>

### 随机打散，重新排序

In [6]:
#将有序数据打散为随机数据
idx = tf.range(10)
idx = tf.random.shuffle(idx)
idx

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([2, 4, 8, 6, 9, 5, 7, 0, 1, 3], dtype=int32)>

In [7]:
a = tf.random.normal([10,784])
a

<tf.Tensor: shape=(10, 784), dtype=float32, numpy=
array([[-0.9299029 ,  0.49135467, -1.2226157 , ..., -0.7259691 ,
        -0.33966008,  0.7572307 ],
       [-0.96837085,  0.21216269, -0.12662534, ..., -1.1766415 ,
         1.0390546 ,  1.1189649 ],
       [-0.06219177, -0.20122664,  0.8502795 , ...,  0.9378708 ,
         0.04291908, -1.0996836 ],
       ...,
       [-0.08840013, -1.3554206 , -2.4231486 , ...,  0.16381386,
         0.31545034, -1.2660487 ],
       [ 1.4954122 ,  0.44216484, -1.6764663 , ...,  1.294794  ,
        -1.2536628 ,  1.0885814 ],
       [ 0.44097465,  1.1079262 ,  0.11285356, ..., -0.48562962,
         0.55329156, -1.217269  ]], dtype=float32)>

In [10]:
#将数据a按照idx的顺序进行重新排列
a = tf.gather(a,idx)
a

<tf.Tensor: shape=(10, 784), dtype=float32, numpy=
array([[-0.06219177, -0.20122664,  0.8502795 , ...,  0.9378708 ,
         0.04291908, -1.0996836 ],
       [-1.5431508 ,  0.752396  , -1.4547589 , ...,  0.32239193,
        -0.03295283,  1.7720162 ],
       [ 1.4954122 ,  0.44216484, -1.6764663 , ...,  1.294794  ,
        -1.2536628 ,  1.0885814 ],
       ...,
       [-0.9299029 ,  0.49135467, -1.2226157 , ..., -0.7259691 ,
        -0.33966008,  0.7572307 ],
       [-0.96837085,  0.21216269, -0.12662534, ..., -1.1766415 ,
         1.0390546 ,  1.1189649 ],
       [ 0.5611659 ,  0.4494363 , -0.543399  , ..., -0.243748  ,
         0.05764265,  0.9853415 ]], dtype=float32)>

In [13]:
b = tf.random.uniform([10],maxval=10,dtype=tf.int32)
b

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 8, 8, 7, 0, 3, 4, 0, 7, 3], dtype=int32)>

In [14]:
#将数据b按照idx进行重新排列
b = tf.gather(b,idx)
b

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([8, 0, 7, 4, 3, 3, 0, 0, 8, 7], dtype=int32)>

### 层数转化

In [5]:
#八层转十层
from tensorflow.keras import layers
net = layers.Dense(10)
net.build((4,8))
net.kernel

<tf.Variable 'kernel:0' shape=(8, 10) dtype=float32, numpy=
array([[ 0.10911763,  0.35701847,  0.40989023, -0.1893098 ,  0.03484499,
         0.23522526, -0.34137416, -0.32569885,  0.46713734, -0.34513408],
       [-0.47500354, -0.4842482 , -0.5336024 , -0.5637996 , -0.24854434,
         0.450418  ,  0.5126504 ,  0.28120506,  0.00978357, -0.09500951],
       [ 0.01626909,  0.01552624,  0.03981847,  0.08473092, -0.5204427 ,
         0.11773199, -0.16021505, -0.21835363, -0.48588032, -0.45857903],
       [-0.08048826, -0.57390785, -0.02906132,  0.15881252,  0.02373528,
         0.5207101 , -0.21778128,  0.43202353,  0.375602  , -0.18112534],
       [-0.01559544,  0.5462053 ,  0.05297405, -0.4756856 , -0.3322941 ,
        -0.10854045,  0.01806325, -0.05438495,  0.23462206,  0.34537196],
       [ 0.07617003, -0.42605856,  0.57654   , -0.49504045, -0.00144577,
         0.4823954 ,  0.30136424,  0.20466685,  0.24565905,  0.23276943],
       [ 0.56071925, -0.23516425, -0.02401197, -0.53910625

In [6]:
net.bias

<tf.Variable 'bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>

### Matrix

In [7]:
x = tf.random.normal([4,784])
x

<tf.Tensor: shape=(4, 784), dtype=float32, numpy=
array([[-0.4500941 ,  0.32838732,  1.4113399 , ..., -0.6685712 ,
        -3.373688  , -1.6136944 ],
       [-1.6924027 , -1.2321968 , -0.6616497 , ..., -0.83970195,
        -0.5760468 ,  0.95179445],
       [ 0.01193128, -0.4524589 , -1.85177   , ...,  1.3748972 ,
        -1.1213125 , -1.868295  ],
       [-0.91101074, -1.2331212 ,  1.1559508 , ...,  1.0902451 ,
         0.11016381, -0.8117533 ]], dtype=float32)>

In [8]:
net = layers.Dense(10)    #目标层的维度
net.build((4,784))

In [9]:
net(x).shape

TensorShape([4, 10])

In [10]:
net.kernel.shape       #784维转化为10维

TensorShape([784, 10])

In [11]:
net.bias.shape

TensorShape([10])

### 卷积层的作用

In [12]:
#假设有一个图片数据
x = tf.random.normal((4,32,32,3))        #3通道RGB，32宽，32高，一共4张图片

In [13]:
net = layers.Conv2D(16,kernel_size=3)      #卷积，将数据维度拓宽

In [14]:
net(x)          #(4, 30, 30, 16)

<tf.Tensor: shape=(4, 30, 30, 16), dtype=float32, numpy=
array([[[[-4.58865404e-01, -5.85944951e-01, -1.99445605e-01, ...,
          -5.02974033e-01,  3.82284760e-01, -5.51193237e-01],
         [-3.48005980e-01, -2.28331164e-01, -1.66215882e-01, ...,
          -3.43091935e-01, -2.98749387e-01, -9.66000676e-01],
         [-1.43194571e-01, -6.10094070e-01,  8.80040135e-03, ...,
           6.52177393e-01, -2.29344312e-02,  1.93366438e-01],
         ...,
         [-2.68421382e-01, -5.42865217e-01, -4.55888845e-02, ...,
          -2.31650751e-02, -9.22039509e-01,  3.91651094e-01],
         [-4.09546733e-01,  2.29933679e-01, -5.26370525e-01, ...,
           2.11407527e-01,  2.47014791e-01, -7.76812375e-01],
         [ 2.64783770e-01, -5.09380817e-01,  1.41332340e+00, ...,
           2.43796431e-03,  1.15876222e+00,  3.64820272e-01]],

        [[-8.05546939e-01, -5.05626261e-01,  9.93004382e-01, ...,
          -6.46281540e-01, -1.46254814e+00,  1.13291955e+00],
         [-2.73583859e-01, -5.9

### 数据维度的意义

#### 三维数据
[6,5,5]   :    5个编码值，5个单词，6个句子 

#### 四维数据
[4,32,32,3] :   3个RGB通道，32个单位长度的宽度，32个高度，4张照片