In [4]:
import tensorflow as tf

In [3]:
%pip install tensorflow-gpu

     |████████████████████████████████| 394.3 MB 5.1 kB/s eta 0:00:01     |█████                           | 61.7 MB 3.9 MB/s eta 0:01:26     |██████████████                  | 172.6 MB 3.4 MB/s eta 0:01:06     |████████████████▏               | 199.3 MB 3.3 MB/s eta 0:00:59�████████▎           | 250.0 MB 3.3 MB/s eta 0:00:44
     |████████████████████████████████| 10.6 MB 24 kB/s s eta 0:00:01
     |████████████████████████████████| 1.0 MB 59.7 MB/s eta 0:00:01
     |████████████████████████████████| 65 kB 3.6 MB/s  eta 0:00:01
     |████████████████████████████████| 57 kB 3.8 MB/s  eta 0:00:01
     |████████████████████████████████| 127 kB 42.8 MB/s eta 0:00:01
     |████████████████████████████████| 462 kB 54.3 MB/s eta 0:00:01
     |████████████████████████████████| 14.8 MB 45.9 MB/s eta 0:00:01
     |████████████████████████████████| 42 kB 721 kB/s  eta 0:00:01
     |████████████████████████████████| 3.8 MB 27.0 MB/s eta 0:00:01
     |████████████████████████████████| 2.9 MB 57.7 

In [2]:
#通过numpy创建
import numpy as np

In [3]:
tf.convert_to_tensor(np.ones([2,3]))

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]])>

In [4]:
tf.convert_to_tensor(np.zeros([2,3]))

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]])>

In [5]:
tf.convert_to_tensor([1,2])

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [6]:
#注意，数据类型需要一致
tf.convert_to_tensor([1,(1,2)])

ValueError: Can't convert Python sequence with mixed types to Tensor.

## 直接通过tensorflow创建

In [7]:

tf.zeros([])    #创建一个标量

<tf.Tensor: shape=(), dtype=float32, numpy=0.0>

In [8]:
tf.zeros([1])     #创建一个1维数据

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>

In [9]:
#注意，这里的[2,3]不是数据，而是要创建的数据的shape
tf.zeros([2,3])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [12]:
a = tf.ones([2,3,3])
a

<tf.Tensor: shape=(2, 3, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [13]:
#创建一个shape相同，数据全0的数据
tf.zeros_like(a)

<tf.Tensor: shape=(2, 3, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

In [14]:
tf.ones([2,3])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

### 填充任意元素

In [15]:
tf.fill([2,2],10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 10],
       [10, 10]], dtype=int32)>

In [16]:
tf.fill([3,5],2.1)

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[2.1, 2.1, 2.1, 2.1, 2.1],
       [2.1, 2.1, 2.1, 2.1, 2.1],
       [2.1, 2.1, 2.1, 2.1, 2.1]], dtype=float32)>

### 创建正态分布数据

In [17]:
tf.random.normal([2,2],mean=1,stddev=1)    #均值为1方差1

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.08492291,  1.239416  ],
       [ 2.5550785 ,  1.6184435 ]], dtype=float32)>

In [18]:
tf.random.normal([2,2])      #标准正态分布

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.19012694,  0.7920874 ],
       [ 0.531189  , -0.17139138]], dtype=float32)>

In [19]:
tf.random.truncated_normal([2,2],mean=0,stddev=1)       #截断的正态分布

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.16926305, -1.0626482 ],
       [-0.9450281 ,  1.242686  ]], dtype=float32)>

### 均匀分布Uniform

In [21]:
tf.random.uniform([2,2],minval=0,maxval=1)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.65244544, 0.16029215],
       [0.3045181 , 0.5259417 ]], dtype=float32)>

In [22]:
tf.random.uniform([3,3],minval=-10,maxval=10)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-8.781815 , -3.3983183, -2.4781322],
       [ 5.9951134, -5.4604363,  6.318199 ],
       [ 9.132616 , -7.7978683,  4.476263 ]], dtype=float32)>

In [24]:
tf.random.uniform([3,3],minval=-10,maxval=10,dtype=tf.int32)    #指定数据类型

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[-3,  5,  1],
       [ 7,  3,  0],
       [ 8,  9, -4]], dtype=int32)>

### 随机打散，重新排序

In [6]:
#将有序数据打散为随机数据
idx = tf.range(10)
idx = tf.random.shuffle(idx)
idx

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([2, 4, 8, 6, 9, 5, 7, 0, 1, 3], dtype=int32)>

In [7]:
a = tf.random.normal([10,784])
a

<tf.Tensor: shape=(10, 784), dtype=float32, numpy=
array([[-0.9299029 ,  0.49135467, -1.2226157 , ..., -0.7259691 ,
        -0.33966008,  0.7572307 ],
       [-0.96837085,  0.21216269, -0.12662534, ..., -1.1766415 ,
         1.0390546 ,  1.1189649 ],
       [-0.06219177, -0.20122664,  0.8502795 , ...,  0.9378708 ,
         0.04291908, -1.0996836 ],
       ...,
       [-0.08840013, -1.3554206 , -2.4231486 , ...,  0.16381386,
         0.31545034, -1.2660487 ],
       [ 1.4954122 ,  0.44216484, -1.6764663 , ...,  1.294794  ,
        -1.2536628 ,  1.0885814 ],
       [ 0.44097465,  1.1079262 ,  0.11285356, ..., -0.48562962,
         0.55329156, -1.217269  ]], dtype=float32)>

In [10]:
#将数据a按照idx的顺序进行重新排列
a = tf.gather(a,idx)
a

<tf.Tensor: shape=(10, 784), dtype=float32, numpy=
array([[-0.06219177, -0.20122664,  0.8502795 , ...,  0.9378708 ,
         0.04291908, -1.0996836 ],
       [-1.5431508 ,  0.752396  , -1.4547589 , ...,  0.32239193,
        -0.03295283,  1.7720162 ],
       [ 1.4954122 ,  0.44216484, -1.6764663 , ...,  1.294794  ,
        -1.2536628 ,  1.0885814 ],
       ...,
       [-0.9299029 ,  0.49135467, -1.2226157 , ..., -0.7259691 ,
        -0.33966008,  0.7572307 ],
       [-0.96837085,  0.21216269, -0.12662534, ..., -1.1766415 ,
         1.0390546 ,  1.1189649 ],
       [ 0.5611659 ,  0.4494363 , -0.543399  , ..., -0.243748  ,
         0.05764265,  0.9853415 ]], dtype=float32)>

In [13]:
b = tf.random.uniform([10],maxval=10,dtype=tf.int32)
b

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 8, 8, 7, 0, 3, 4, 0, 7, 3], dtype=int32)>

In [14]:
#将数据b按照idx进行重新排列
b = tf.gather(b,idx)
b

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([8, 0, 7, 4, 3, 3, 0, 0, 8, 7], dtype=int32)>