In [1]:
%pip install tensorflow

     |████████████████████████████████| 394.3 MB 13 kB/s s eta 0:00:01
     |████████████████████████████████| 42 kB 2.1 MB/s  eta 0:00:01
     |████████████████████████████████| 10.6 MB 48.9 MB/s eta 0:00:01
     |████████████████████████████████| 1.0 MB 75.7 MB/s eta 0:00:01
     |████████████████████████████████| 462 kB 65.2 MB/s eta 0:00:01
     |████████████████████████████████| 3.8 MB 51.0 MB/s eta 0:00:01
     |████████████████████████████████| 2.9 MB 76.0 MB/s eta 0:00:01
     |████████████████████████████████| 57 kB 8.6 MB/s  eta 0:00:01
     |████████████████████████████████| 65 kB 7.1 MB/s  eta 0:00:01
     |████████████████████████████████| 127 kB 61.9 MB/s eta 0:00:01
     |████████████████████████████████| 14.8 MB 44.0 MB/s eta 0:00:01
     |████████████████████████████████| 781 kB 41.4 MB/s eta 0:00:01
     |████████████████████████████████| 96 kB 411 kB/s  eta 0:00:01
     |████████████████████████████████| 116 kB 39.2 MB/s eta 0:00:01
     |████████████████████████████

In [2]:
import tensorflow as tf

In [3]:
#整型
tf.constant(1)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [4]:
#浮点型
tf.constant(1.)

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [5]:
#类型不对会报错
tf.constant(2.2,dtype=tf.int32)

TypeError: Cannot convert 2.2 to EagerTensor of dtype int32

In [6]:
tf.constant(1.2,dtype=tf.double)

<tf.Tensor: shape=(), dtype=float64, numpy=1.2>

In [8]:
#布尔型
tf.constant([True,False])

<tf.Tensor: shape=(2,), dtype=bool, numpy=array([ True, False])>

In [11]:
#1或0不能转化为bool型
tf.constant(1,dtype=tf.bool)

TypeError: Cannot convert [0] to EagerTensor of dtype bool

In [12]:
tf.constant('hello world')

<tf.Tensor: shape=(), dtype=string, numpy=b'hello world'>

In [16]:
#选择在cpu上操作
with tf.device('cpu'):
    a = tf.constant([1])

#选择再GPU上操作
with tf.device('gpu'):
    b = tf.range(4)

In [14]:
a.device

'/job:localhost/replica:0/task:0/device:CPU:0'

In [15]:
b.device

'/job:localhost/replica:0/task:0/device:CPU:0'

In [17]:
#cpu转换到gpu上
aa = a.gpu()

Instructions for updating:
Use tf.identity instead.


RuntimeError: GPU:0 unknown device.

In [18]:
#gpu转换到cpu上
bb = b.cpu()

Instructions for updating:
Use tf.identity instead.


In [19]:
b.ndim

1

In [20]:
#判断是否为tensor数据
tf.is_tensor(a)

True

In [22]:
import numpy as np
b = np.array([1.,2.,3.])
tf.is_tensor(b)

False

In [23]:
#普通数据类型转换为tensor
bb = tf.convert_to_tensor(b)
tf.is_tensor(bb)

True

In [24]:
bb

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1., 2., 3.])>

In [25]:
#不同数据类型互相转换
tf.cast(bb,dtype=tf.int32)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [27]:
tf.cast(bb,dtype=tf.float32)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [31]:
tf.cast(bb,dtype=tf.double)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1., 2., 3.])>

In [34]:
a = tf.range(5)
a

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4], dtype=int32)>

In [35]:
#将tensor数据a转换为可自动求导的数据b，为Variable类型
b = tf.Variable(a)

In [36]:
b.dtype

tf.int32

In [37]:
b.name

'Variable:0'

In [38]:
b = tf.Variable(a,name='input_data')

In [39]:
b.name

'input_data:0'

In [40]:
#b可训练
b.trainable

True

In [45]:
isinstance(b,tf.Variable)    #可用来判断数据b是否可自动求导

True

In [47]:
isinstance(b,tf.Tensor)

False

In [43]:
#本质上还是tensor数据
tf.is_tensor(b)

True

In [42]:
b.numpy()

array([0, 1, 2, 3, 4], dtype=int32)